### ISSUE TITLE
your S3 link is not working

### ISSUE THREAD

**Issue by IanniMuliterno** [vishalmhjn/traffic-waves#1]
your S3 link is leading to a #403 error.

**Comment by vishalmhjn** [comment]
Thanks a lot for checking out my repo. Yes, a while ago, I disabled S3 public access and deleted the other AWS resources. Right now, I am making few changes to the set-up and then I will again make it accessible soon.

**Comment by vishalmhjn** [comment]
Hi @IanniMuliterno, I have restored the S3 link for now. (Later, to avoid any case of unexpected costs, I might take it down again)

**Comment by IanniMuliterno** [comment]
thanks, I am going to check it out. Congrats on your project, it helped me learning
